### ISSUE TITLE
USB ports do not switch of with setMaxCurrentsFixed(0, 0, 0, 0, 0)

### ISSUE THREAD

**Issue by twischer** [happyme531/h1_SW35xx#1]
Sometimes the output voltage is limited to 5V. But I was not yet able to switch the USB ports completely off.
Are you able to switch the USB outputs off via I2C?

My SW3518 IC contains 0x07 in the IC_VERSION register.
The only documentation I found so far is [1].
Looks like the documentation I found in [1] differs with your implementation. (Especially with register SW35XX_PD_CONF1)
Do you have any additional information?

I would be quite happy about any hint you could give.

[1] https://hackaday.io/project/176558-extra-info-sw3516-sw3518-dcdc-w-pd3-pps-qc3

**Comment by happyme531** [comment]
Get a newer version of the register document here. This is what I use to write the library.
[sw35xx_reg.pdf](https://github.com/happyme531/h1_SW35xx/files/7046141/sw35xx_reg.pdf)

Unfortunately I haven't found any register that control the port on/off yet.

**Comment by twischer** [comment]
Thanks a lot
