### ISSUE TITLE
SW3518S寄存器手册更新

### ISSUE THREAD

**Issue by SaltyFishOnTheSea** [happyme531/h1_SW35xx#6]
官方的寄存器列表更新v2.3，多了几个v2.1没有的寄存器

[SW3518S_寄存器列表_Release_RG003_2_v2.3.pdf](https://github.com/happyme531/h1_SW35xx/files/11593338/SW3518S_._Release_RG003_2_v2.3.pdf)

**Comment by uptell8** [comment]
vin输入电压读取不了，我查看了一下手册6. REG 0x30: ADC Vin 数据
Bit Description R/W Default
7-0 vin 电压的高 8bit, 
160mv/bit; (若取 12bit 时分辨率为 10mv/bit,参见 reg0x3A)
注意默认 vin 的数据不能读出, 需要写 reg0x13[1]为 1.

**Comment by happyme531** [comment]
> 官方的寄存器列表更新v2.3，多了几个v2.1没有的寄存器
> 
> [SW3518S_寄存器列表_Release_RG003_2_v2.3.pdf](https://github.com/happyme531/h1_SW35xx/files/11593338/SW3518S_._Release_RG003_2_v2.3.pdf)

感谢提供宝贵的资料！

**Comment by scccx8106** [comment]
有没有3516的资料，谢谢
