### ISSUE TITLE
vin输入电压读取不了

### ISSUE THREAD

**Issue by uptell8** [happyme531/h1_SW35xx#7]
vin输入电压读取不了，我查看了一下手册6.REG 0x30： ADC VIN 数据 位
描述 R/W 默认
7-0 vin 电压的高 8bit，
160mv/bit;（若取 12bit 时分辨率为 10mv/bit，参见 reg0x3A）
注意默认 vin 的数据不能读出， 需要写 reg0x13[1]为 1.

**Comment by happyme531** [comment]
https://github.com/happyme531/h1_SW35xx/blob/966729ad376f954d03f8f14e8d9715e30e4cddf4/src/h1_SW35xx.cpp#LL94C1-L99C1

是不是没有调用begin()?

**Comment by uptell8** [comment]
感谢您的回复，这是使用您的实例测试的，其他的都正常，就是vin读取为0，我是刚接触编程的小白，如有打扰还望见谅
=======================================
Current input voltage:0mV
Current output voltage:9162mV
Current USB-C current:1337mA
Current USB-A current:0mA
Current fast charge type:PD Fix
Current PD version:2
=======================================

**Comment by uptell8** [comment]
抱歉，是我的问题，问题已经解决，再次感谢您的回答！
