### ISSUE TITLE
Cannot read input voltage register on sw3518s

### ISSUE THREAD

**Issue by Tanamichi** [happyme531/h1_SW35xx#9]
Hello, I glad to use this library with my own project.
I'm using charger module based on sw3518s(VOOC support) and i cannot see input voltage. sw3518s processing input voltage for set PD available modes. I'm using laboratory power supply and setting different voltages have react to PD table directly.
if you have a sw3518s, can you check this out?

**Comment by happyme531** [comment]
https://github.com/happyme531/h1_SW35xx/blob/966729ad376f954d03f8f14e8d9715e30e4cddf4/src/h1_SW35xx.cpp#L95C1-L98C2
```cpp
void SW35xx::begin(){
  //启用输入电压读取
  i2cWriteReg8(SW35XX_I2C_CTRL, 0x02);
}
```
Normally the input voltage read will be enabled once SW35xx::begin() is called. Try check your code for this.

**Comment by Tanamichi** [comment]
this code present in default and i'm double checked this.
I have zero value in "vin" variable. 
also i tried add unlock_i2c_write(); and lock_i2c_write(); around i2cWriteReg8.
Still nothing happened, i see zero value ;(
Fixed: 

I moved ```i2cWriteReg8(SW35XX_I2C_CTRL, 0x02); ``` from constructor to another public method and call him after Wire init with small delay. It's worked for me.  

You can close this issue

**Comment by happyme531** [comment]
So it is probably a timing issue...
